server:
  port: 7075
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${rabbit_user}
    password: ${rabbit_pw}
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${company_mail}
    password: ${company_pw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#Değişkenler:
rabbitmq:
  mail-queue: mailQueue

mail-service:
  company: ${company_mail}
