#server:
#  port: 80
#
#spring:
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411
#    service:
#      name: api-gateway-service
#  main:
#    web-application-type: reactive
#  application:
#    name: api-gateway-service
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins: "*"
#            allowed-headers: "*"
#            allowed-methods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#      routes:
#        - id: auth-service
#          predicates:
#            - Path=/auth/**
#          uri: http://localhost:7071
#          filters:
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#            - name: CircuitBreaker
#              args:
#                enabled: true
#                fallbackUri: forward:/fallback/authservice
#        - id: user-service
#          predicates:
#            - Path=/user/**
#          uri: http://localhost:7072
#          filters:
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#            - name: CircuitBreaker
#              args:
#                enabled: true
#                fallbackUri: forward:/fallback/userservice
#        - id: shift-service
#          predicates:
#            - Path=/shift/**
#          uri: http://localhost:7072
#          filters:
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#            - name: CircuitBreaker
#              args:
#                enabled: true
#                fallbackUri: forward:/fallback/userservice
#        - id: company-service
#          predicates:
#            - Path=/company/**
#          uri: http://localhost:7073
#          filters:
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#            - name: CircuitBreaker
#              args:
#                enabled: true
#                fallbackUri: forward:/fallback/companyworksservice
#        - id: file-service
#          predicates:
#            - Path=/files/**
#          uri: http://localhost:7073
#          filters:
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#            - name: CircuitBreaker
#              args:
#                enabled: true
#                fallbackUri: forward:/fallback/companyworksservice
#        - id: transaction-service
#          predicates:
#            - Path=/transaction/**
#          uri: http://localhost:7073
#          filters:
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#            - name: CircuitBreaker
#              args:
#                enabled: true
#                fallbackUri: forward:/fallback/companyworksservice
#        - id: comment-service
#          predicates:
#            - Path=/comment/**
#          uri: http://localhost:7073
#          filters:
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#            - name: CircuitBreaker
#              args:
#                enabled: true
#                fallbackUri: forward:/fallback/companyworksservice
#        - id: leave-service
#          predicates:
#            - Path=/leave/**
#          uri: http://localhost:7073
#          filters:
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#            - name: CircuitBreaker
#              args:
#                enabled: true
#                fallbackUri: forward:/fallback/companyworksservice
#      default-filters:
#        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}
#

spring:
  cloud:
    config:
      uri: ${CONFIG_URL}
  config:
    import: "configserver:"
  application:
    name: api-gateway-application